---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Сайт должен быть доступен на различных устройствах

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины


implicit:
  - У сайта должна быть возможность регистрации, авторизации и аутентификации пользователя
  - У пользователя должна быть возможность оформить заказ с переходом на страницу оплаты
  - У пользователя при оформлении заказа должны быть запрошены контактные данные
  - Корзина должна храниться в сессии браузера
  - В списке товаров кнопка "Заказать" открывает модальное окно с возможностью ввести количество товара и кнопкой добавления товара в корзину
  - При добавлении товара в корзину появляется сообщение в углу об успешном добавлении товара в корзину
  - При переходе в корзину показывается список добавленных товаров и кнопка заказа товаров
  - При подтверждении заказа все данные о заказе отправляются на сервер
  - После подтверждения заказа появляется сообщение об успешном оформлении заказа
  - Нельзя оформить пустой заказ